import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/header';
import { Toaster } from '@/components/ui/sonner';
import { SessionProvider } from 'next-auth/react';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={` antialiased`}
      >
        <SessionProvider>
          <Header />
          <main className='h-[calc(100vh-60px)] p-5 flex-col'>{children}</main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
